services:
  configsvr:
    image: mongo:4.4.0-bionic
    container_name: configsvr
    command: ["mongod", "--configsvr", "--replSet", "rsConfig", "--port", "27019"]
    ports:
      - 27019:27019
    volumes:
      - configsvr:/data/db

  shard1:
    image: mongo:4.4.0-bionic
    container_name: shard1
    command: ["mongod", "--shardsvr", "--replSet", "rsShard1", "--port", "27018"]
    ports:
      - 27018:27018
    volumes:
      - shard1:/data/db

  shard2:
    image: mongo:4.4.0-bionic
    container_name: shard2
    command: ["mongod", "--shardsvr", "--replSet", "rsShard2", "--port", "27018"]
    ports:
      - 27020:27018
    volumes:
      - shard2:/data/db

  shard3:
    image: mongo:4.4.0-bionic
    container_name: shard3
    command: ["mongod", "--shardsvr", "--replSet", "rsShard3", "--port", "27018"]
    ports:
      - 27021:27018
    volumes:
      - shard3:/data/db

  shard4:
    image: mongo:4.4.0-bionic
    container_name: shard4
    command: ["mongod", "--shardsvr", "--replSet", "rsShard4", "--port", "27018"]
    ports:
      - 27022:27018
    volumes:
      - shard4:/data/db

  mongos:
    image: mongo:4.4.0-bionic
    container_name: mongos
    command: ["mongos", "--configdb", "rsConfig/configsvr:27019", "--port", "27017"]
    ports:
      - 27017:27017
    depends_on:
      - configsvr
      - shard1
      - shard2
      - shard3
      - shard4

volumes:
  configsvr:
  shard1:
  shard2:
  shard3:
  shard4:
